### ISSUE TITLE
bug: @astro-community/astro-embed-twitter - cannot read properties of undefined reading `urls`

### ISSUE THREAD

**Issue by nirtamir2** [astro-community/astro-embed#27]
Hi
I tried this package and it work most of the times.
For some reason, this tweet `<Tweet id="https://twitter.com/addyosmani/status/1600553460180869120" />` URL does not work.
I get the error
`Cannot read properties of undefined (reading 'urls')`

Notice that this tweet is valid
![image](https://user-images.githubusercontent.com/16452789/208268818-25ab24a4-16f6-4143-892a-56da7c003c2e.png)

<details>
<summary>Error Image Details</summary>

![image](https://user-images.githubusercontent.com/16452789/208268749-fbe46ae1-654b-4205-a519-6850c744afd8.png)

</details>

```
Cannot read properties of undefined (reading 'urls')
/node_modules/.pnpm/@astro-community+astro-embed-twitter@0.2.0_astro@1.6.2/node_modules/@astro-community/astro-embed-twitter/Tweet.astro:79:30
TypeError: Cannot read properties of undefined (reading 'urls')
    at buildContent (/node_modules/.pnpm/@astro-community+astro-embed-twitter@0.2.0_astro@1.6.2/node_modules/@astro-community/astro-embed-twitter/Tweet.astro:79:30)
    at eval (/node_modules/.pnpm/@astro-community+astro-embed-twitter@0.2.0_astro@1.6.2/node_modules/@astro-community/astro-embed-twitter/Tweet.astro:148:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.renderToString (/node_modules/.pnpm/astro@1.6.2_ts-node@10.9.1/node_modules/astro/dist/runtime/server/render/astro.js:66:21)
    at async renderJSX (/node_modules/.pnpm/astro@1.6.2_ts-node@10.9.1/node_modules/astro/dist/runtime/server/jsx.js:49:53)
    at async Promise.all (index 1)
    at async renderJSX (/node_modules/.pnpm/astro@1.6.2_ts-node@10.9.1/node_modules/astro/dist/runtime/server/jsx.js:28:10)
    at async renderElement (/node_modules/.pnpm/astro@1.6.2_ts-node@10.9.1/node_modules/astro/dist/runtime/server/jsx.js:152:133)
    at async renderJSX (/node_modules/.pnpm/astro@1.6.2_ts-node@10.9.1/node_modules/astro/dist/runtime/server/jsx.js:54:53)
    at async Promise.all (index 1)
```

I think the solution to this is to check if `entities` exists first because its hard to trust Twitter API types in the tests that I run playing with this API myself.

https://github.com/astro-community/astro-embed/blob/main/packages/astro-embed-twitter/Tweet.astro#L87

like that `if (tweet.data.entities?.urls) {`

**Comment by delucis** [comment]
Thanks for the bug report! Guess we’d need that `?.` optional chaining each time we read off `entities`. Would you like to open a PR fixing this?

**Comment by nirtamir2** [comment]
Sure!

**Comment by nirtamir2** [comment]
@delucis see https://github.com/astro-community/astro-embed/pull/28

**Comment by delucis** [comment]
Thanks again @nirtamir2! The fix for this should be available in the latest release.
